/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _COUNT_H_RPCGEN
#define _COUNT_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct Output {
	int characters;
	int words;
	int lines;
	int errorCode;
};
typedef struct Output Output;

struct Input {
	char *directory;
	int threshold;
};
typedef struct Input Input;

#define COUNTPROGRAM 0x20000015
#define CONTAVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define CONTA 1
extern  Output * conta_1(char **, CLIENT *);
extern  Output * conta_1_svc(char **, struct svc_req *);
#define CONTA_FILE 2
extern  int * conta_file_1(Input *, CLIENT *);
extern  int * conta_file_1_svc(Input *, struct svc_req *);
extern int countprogram_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define CONTA 1
extern  Output * conta_1();
extern  Output * conta_1_svc();
#define CONTA_FILE 2
extern  int * conta_file_1();
extern  int * conta_file_1_svc();
extern int countprogram_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Output (XDR *, Output*);
extern  bool_t xdr_Input (XDR *, Input*);

#else /* K&R C */
extern bool_t xdr_Output ();
extern bool_t xdr_Input ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_COUNT_H_RPCGEN */
