/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "scan.h"

bool_t
xdr_Output(xdrs, objp)
	XDR *xdrs;
	Output *objp;
{
	int32_t *buf;

	if (xdrs->x_op == XDR_ENCODE) {
		buf = (int32_t *)XDR_INLINE(xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			if (!xdr_int(xdrs, &objp->caratteri))
				return (FALSE);
			if (!xdr_int(xdrs, &objp->parole))
				return (FALSE);
			if (!xdr_int(xdrs, &objp->linee))
				return (FALSE);
			if (!xdr_int(xdrs, &objp->errore))
				return (FALSE);
		} else {
			IXDR_PUT_LONG(buf, objp->caratteri);
			IXDR_PUT_LONG(buf, objp->parole);
			IXDR_PUT_LONG(buf, objp->linee);
			IXDR_PUT_LONG(buf, objp->errore);
		}
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = (int32_t *)XDR_INLINE(xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			if (!xdr_int(xdrs, &objp->caratteri))
				return (FALSE);
			if (!xdr_int(xdrs, &objp->parole))
				return (FALSE);
			if (!xdr_int(xdrs, &objp->linee))
				return (FALSE);
			if (!xdr_int(xdrs, &objp->errore))
				return (FALSE);
		} else {
			objp->caratteri = IXDR_GET_LONG(buf);
			objp->parole = IXDR_GET_LONG(buf);
			objp->linee = IXDR_GET_LONG(buf);
			objp->errore = IXDR_GET_LONG(buf);
		}
	} else {
		if (!xdr_int(xdrs, &objp->caratteri))
			return (FALSE);
		if (!xdr_int(xdrs, &objp->parole))
			return (FALSE);
		if (!xdr_int(xdrs, &objp->linee))
			return (FALSE);
		if (!xdr_int(xdrs, &objp->errore))
			return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_Input(xdrs, objp)
	XDR *xdrs;
	Input *objp;
{

	if (!xdr_string(xdrs, &objp->directory, 50))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->soglia))
		return (FALSE);
	return (TRUE);
}
