/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SCAN_H_RPCGEN
#define _SCAN_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct Output {
	int caratteri;
	int parole;
	int linee;
	int errore;
};
typedef struct Output Output;

struct Input {
	char *directory;
	int soglia;
};
typedef struct Input Input;

#define SCANPROGRAM 0x20000015
#define SCANVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define file_scan 1
extern  Output * file_scan_1(char **, CLIENT *);
extern  Output * file_scan_1_svc(char **, struct svc_req *);
#define dir_scan 2
extern  int * dir_scan_1(Input *, CLIENT *);
extern  int * dir_scan_1_svc(Input *, struct svc_req *);
extern int scanprogram_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define file_scan 1
extern  Output * file_scan_1();
extern  Output * file_scan_1_svc();
#define dir_scan 2
extern  int * dir_scan_1();
extern  int * dir_scan_1_svc();
extern int scanprogram_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Output (XDR *, Output*);
extern  bool_t xdr_Input (XDR *, Input*);

#else /* K&R C */
extern bool_t xdr_Output ();
extern bool_t xdr_Input ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SCAN_H_RPCGEN */
